package com.pointerlocation

import com.facebook.react.bridge.ReactApplicationContext

/**
 * New Architecture spec.
 *
 * NativePointerLocationSpec is auto-generated by React Native's codegen from
 * src/NativePointerLocation.ts. It provides type-safe abstract method declarations
 * that match the TypeScript spec (setShowTaps, setPointerLocation).
 *
 * This file is only compiled when newArchEnabled=true (see build.gradle sourceSets).
 */
abstract class PointerLocationSpec internal constructor(context: ReactApplicationContext) :
  NativePointerLocationSpec(context)
