/**
 * Objective-C header for the PointerLocation TurboModule.
 *
 * This file is ONLY compiled when the New Architecture is enabled (RCT_NEW_ARCH_ENABLED).
 * It declares the PointerLocation class as conforming to the NativePointerLocationSpec protocol,
 * which is auto-generated by React Native's codegen from src/NativePointerLocation.ts.
 *
 * On the Old Architecture, this file is entirely skipped (#ifdef guard), and the
 * PointerLocation class is instead declared inline in PointerLocation.mm using
 * the RCT_EXPORT_MODULE / RCT_EXPORT_METHOD macros.
 *
 * The codegen-generated spec lives in the PointerLocationSpec pod/framework.
 */

#ifdef RCT_NEW_ARCH_ENABLED

// Import the codegen-generated Objective-C protocol.
// This protocol declares methods like setShowTaps: and setPointerLocation:
// that our implementation must provide.
#import <PointerLocationSpec/PointerLocationSpec.h>

// Declare PointerLocation as an NSObject that conforms to NativePointerLocationSpec.
// The actual method implementations are in PointerLocation.mm.
@interface PointerLocation : NSObject <NativePointerLocationSpec>

@end

#endif
